{
 "title": "PVC Storage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PVC Storage Used %",
   "type": "graph",
   "description": "Percent of used space per PVC",
   "gridPos": { "h": 15, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes * 100",
     "legendFormat": "{{ namespace }} :: {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Cluster Total Storage Used",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes) / sum(kubelet_volume_stats_capacity_bytes) * 100",
     "legendFormat": "Total Percent Used"
    }
   ]
  },
  {
   "title": "Current Total Capacity",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 15 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes)",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Current Total Used",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 16, "y": 15 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes)"
    }
   ]
  }
 ]
}