---
#Expose service by ip
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elk
  name: elk
  namespace: elk
spec:
  type: ClusterIP
  clusterIP: 10.100.115.154
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
